### ISSUE TITLE
Backup research and validation

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-operator#385]
Currently, operator seems to include both "velero" and "restic" functionality.

We want it to include support for creating local backups, where Velero seem to be the solution. However, Restic should not be part of version 1.

**Comment by vbradnitski** [comment]
there are 2 ways to do backups:
1. Use our cloud-agent which is based on Restic. 
2. Velero: It can backup the whole cluster, but for volume backups it also uses Restic.

So looks like we should move out cloud-agent from xp-operator before the release because it's private.
+ Velero usage should be documented.
